### ISSUE TITLE
For android, Build.VERSION_CODES.N & setInvalidatedByBiometricEnrollment method not found

### ISSUE THREAD

**Issue by center11** [MaxToyberman/react-native-fingerprint-change#1]
solution：Build.VERSION_CODES.N & setInvalidatedByBiometricEnrollment are required android API level >= 24, @MaxToyberman please update the compileSdkVersion to 24 in react-native-fingerprint-change build.gradle.

modify the  \react-native-fingerprint-change\android\build.gradle, change compileSdkVersion to 24:
android {
    compileSdkVersion **24**
    buildToolsVersion '25.0.0'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

**Comment by MaxToyberman** [comment]
Done , @center11  thank you
