### ISSUE TITLE
Can't detect fingerprint was removed in android 7.0

### ISSUE THREAD

**Issue by center11** [MaxToyberman/react-native-fingerprint-change#2]
@MaxToyberman Hi, the component can't detect fingerprint was removed in android 7.0, any advice?

**Comment by MaxToyberman** [comment]
@center11 I have seen this problem, I need  to make some reasearch on it.

**Comment by amlord** [comment]
@MaxToyberman Hi Maxim, I've just been playing around with this package & it works perfectly for iOS, on Android I always get a response of `false` though. I assume it's down to this issue, did you have chance to look into it at all?

No worries if not, it looks like i'll need to create a package to do something similar as there's not much else out there...

Thanks for the great work though!

**Comment by e55o** [comment]
it seems that it does not detect any change on all android versions, tested on android 9 with no luck,
i'm getting `false` even if i make changes to my stored fingerprints.

**Comment by MaxToyberman** [comment]
Version 1.2.0 was released, please check it out @e55o @amlord @center11

**Comment by e55o** [comment]
Thanks @MaxToyberman, will test it and get back to you.

**Comment by e55o** [comment]
@MaxToyberman i can confirm, it is working now on Android 9, just a question, is it only applied for foreground/background activities? Aren't we able to receive a unique key from the device and store it in asyncStorage, in order to compare when the user opens the app again?

**Comment by MaxToyberman** [comment]
@e55o "Aren't we able to receive a unique key from the device and store it in asyncStorage, in order to compare when the user opens the app again" this is what I am actually doing to detect the fingerprint change.

**Comment by e55o** [comment]
@MaxToyberman so it should work even if the app task got killed and reopened?

**Comment by MaxToyberman** [comment]
@e55o  yes

**Comment by MaxToyberman** [comment]
@e55o in the readme I gave an example on how to handle the background situation, but it the app killed you can call `hasFingerPrintChanged` in componentDidMount maybe.

**Comment by e55o** [comment]
well done! it is working perfectly on android pie 🎉

**Comment by JeffreyLeeDave** [comment]
Can we re-open this? So here are my steps:

1. I set up fingerprint on my device
2. I console log the result of this library and got false
3. I then go to android settings and removed all fingerprints
4. I set up fingerprint again
5. I open my app and console log the result of using this library
6. Still get false each time

I am on version 1.2.5 of this package. I am using api 28 which I believe is Pie. Pixel 2XL emulator on Android Studio

**Comment by JeffreyLeeDave** [comment]
As of today, still encountering that issue.

**Comment by edenmeshulam** [comment]
@JeffreyLeeDave 
Did it solved? 
Still get this false all the time .

**Comment by JeffreyLeeDave** [comment]
I believe it's fixed now. Admittedly I haven't looked at this for awhile
